### ISSUE TITLE
[IDEA] Add the Amass subdomain enumeration tool

### ISSUE THREAD

**Issue by caffix** [rmusser01/Infosec_Reference#12]
Amass is the most In-depth subdomain enumeration tool and performs DNS OSINT. This could fall under the 'General Data Scrapers' section of your awesome list. The Amass project can be found using the link below:

https://github.com/caffix/amass

Thanks in advance!

**Comment by rmusser01** [comment]
Added under 'DNS' in the Network Scanning & Attacks section, with the other DNS related scanning tools. Will be added on next commit. Thanks.
