### ISSUE TITLE
Beginner's Guide to Docs - Permission denied

### ISSUE THREAD

**Issue by megan201296** [rmusser01/Infosec_Reference#15]
One of the first links on the documentation/reporting page is `http://docs.writethedocs.org/writing/beginners-guide-to-docs/` which when visited gives
```
Permission Denied
You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.
```
Not sure if having a link that is not publicly accessible is on purpose or not but figured its worth mentioning.

**Comment by rmusser01** [comment]
Thanks for the heads up, looks like they moved the content from that URL to a different subdomain. I've updated the link in the page to: 'https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/'

**Comment by beerisgood** [comment]
SSL Certificate name mismatch:
https://www.ssllabs.com/ssltest/analyze.html?d=www.writethedocs.org
