### ISSUE TITLE
Link to Linux kernel development(walkthrough) doesn't work

### ISSUE THREAD

**Issue by shantanu-gontia** [rmusser01/Infosec_Reference#22]
Hi,

the link to **Link to Linux kernel development(walkthrough) doesn't work** leads to a 404 Not Found.

**Comment by rmusser01** [comment]
Thank you for the heads up, manually fixed in the current version and changed on my local for next push.

**Comment by rmusser01** [comment]
Until then, here is a working link: https://github.com/0xAX/linux-insides/
