### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [rmusser01/Infosec_Reference#45]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following page: https://github.com/rmusser01/Infosec_Reference/blob/master/Draft/Network_Attacks.md
I wonder if you’d be able to replace it with the new one: https://www.catchpoint.com/blog/mqtt-iot and https://www.catchpoint.com/blog/wireshark-mqtt

Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by rmusser01** [comment]
Yep, done in the local copy and will be updated on the next push. Thanks.
